name: Release

on:
  push:
    tags:
      - 'v*' # Push events matching v1.0, v20.15.10, etc.

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact: windows
            build_cmd: npm run package:win
          - os: ubuntu-latest
            artifact: linux
            build_cmd: npm run package:linux
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse-dev build-essential libasound2-dev libpulse-mainloop-glib0

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build application
        run: ${{ matrix.build_cmd }}

      - name: Find and list build artifacts
        id: find-files
        run: |
          find dist/ -type f -name "*" -exec ls -la {} \;
          echo "ARTIFACTS=$(find dist/ -type f -name "*.exe" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" | tr '\n' ' ')" >> $GITHUB_OUTPUT
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/
          if-no-files-found: error
          retention-days: 1

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: dist/windows
          if-no-files-found: warn

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: dist/linux
          if-no-files-found: warn

      - name: Find and list all files
        run: |
          find . -type f | sort
          echo "--- Contents of dist/ ---"
          ls -la dist/
          echo "--- Contents of dist/windows/ ---"
          ls -la dist/windows/ || echo "No windows directory"
          echo "--- Contents of dist/linux/ ---"
          ls -la dist/linux/ || echo "No linux directory"
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            - New release with pre-built packages for Windows and Linux
            
            ### Download Links
            - **Windows x64**: [volume-control-windows-x64.exe](https://github.com/Volodymyr-Bauzi/PC-Volume-controll-using-mobile/releases/download/${{ github.ref_name }}/volume-control-windows-x64.exe)
            - **Linux x64**: [volume-control-linux-x64](https://github.com/Volodymyr-Bauzi/PC-Volume-controll-using-mobile/releases/download/${{ github.ref_name }}/volume-control-linux-x64)
          draft: false
          prerelease: false
          files: |
            dist/**/*.exe
            dist/**/*.AppImage
            dist/**/*.deb
            dist/**/*.rpm
            dist/**/*.zip
            dist/**/*.dmg

  update-readme:
    name: Update README
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update download links in README
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          sed -i 's|https://github.com/yourusername/volume-control/releases/latest/download/|https://github.com/Volodymyr-Bauzi/PC-Volume-controll-using-mobile/releases/download/${VERSION}/|g' README.md
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update download links for ${GITHUB_REF_NAME}"
          git push
