name: Release

on:
  push:
    tags:
      - 'v*' # Push events matching v1.0, v20.15.10, etc.

permissions:
  contents: write

jobs:
  build:
    name: Build and Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact: windows
            build_cmd: npm run package:win
            dist_dir: win
          - os: ubuntu-latest
            artifact: linux
            build_cmd: npm run package:linux
            dist_dir: linux
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse-dev build-essential libasound2-dev libpulse-mainloop-glib0

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build application
        run: ${{ matrix.build_cmd }}
        
      - name: List files in dist directory
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "--- Contents of dist/ ---"
          ls -la dist/
          echo "--- Contents of dist/${{ matrix.dist_dir }}/ ---"
          ls -la dist/${{ matrix.dist_dir }} || echo "Directory not found"
          
      - name: List files in dist directory (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "--- Contents of dist/ ---"
          Get-ChildItem -Path dist -Force
          echo "--- Contents of dist/${{ matrix.dist_dir }}/ ---"
          if (Test-Path "dist/${{ matrix.dist_dir }}") {
            Get-ChildItem -Path "dist/${{ matrix.dist_dir }}" -Force
          } else {
            echo "Directory not found"
          }

      - name: Create release directory and package release (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p release
          node package-release.js
          
      - name: Create release directory and package release (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -ItemType Directory -Force -Path release | Out-Null
          node package-release.js

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            dist/${{ matrix.dist_dir }}
            release/volume-control-windows-v*.zip
          if-no-files-found: error
          retention-days: 1
          
      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            dist/${{ matrix.dist_dir }}
            release/volume-control-linux-v*.zip
          if-no-files-found: error
          retention-days: 1

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*.zip'
          create-top-level-directory: false

      - name: List downloaded files
        run: find . -type f -name '*.zip' -exec ls -la {} \;

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            ## What's New in ${{ github.ref_name }}
            - Pre-built packages for Windows and Linux
            - Improved packaging and distribution
            
            ### Download Links
            - **Windows x64**: [volume-control-windows-v${{ github.ref_name }}.zip](https://github.com/Volodymyr-Bauzi/PC-Volume-controll-using-mobile/releases/download/${{ github.ref_name }}/volume-control-windows-v${{ github.ref_name }}.zip)
            - **Linux x64**: [volume-control-linux-v${{ github.ref_name }}.zip](https://github.com/Volodymyr-Bauzi/PC-Volume-controll-using-mobile/releases/download/${{ github.ref_name }}/volume-control-linux-v${{ github.ref_name }}.zip)
            
            ### Installation
            1. Download the appropriate zip file for your platform
            2. Extract the zip file
            3. Run the application:
               - Windows: Double-click `volume-control.exe`
               - Linux: Run `chmod +x volume-control` then `./volume-control`
          draft: false
          prerelease: false
          files: |
            artifacts/volume-control-windows-*.zip
            artifacts/volume-control-linux-*.zip

  update-readme:
    name: Update README
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update download links in README
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          sed -i 's|https://github.com/yourusername/volume-control/releases/latest/download/|https://github.com/Volodymyr-Bauzi/PC-Volume-controll-using-mobile/releases/download/${VERSION}/|g' README.md
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update download links for ${GITHUB_REF_NAME}"
          git push
